# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys, math, form

from PyQt6 import QtCore, QtGui, QtWidgets

mr_form = form.Ui_MainWindow()

def main():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = mr_form
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

if __name__ == '__main__':
    main()

def cal():
    print(1)
    P = mr_form.doubleSpinBoxP.value
    V = mr_form.doubleSpinBoxV.value
    T = mr_form.doubleSpinBoxT.value

    S = calculateS(P, V, T)
    print(S)

    mr_form.labelNumS.setText(S)

def calculateS(V, T, P):
    return math.ceil(math.fabs((V*T)/P))

def calculateA(latCap, latUpper, rusCap, rusUpper, symbols, digits):
    return latCap * 26 + latUpper * 26 + rusCap * 33 + rusUpper * 33 + symbols * 33 + digits * 10

def calculateL(A, T, V):
    S = T * V
    L = math.log(S, A)
    return L

mr_form.doubleSpinBoxP.textChanged.connect(cal)