# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys, math, random, string

from PyQt6 import QtCore, QtGui, QtWidgets
from form import Ui_MainWindow

class MainWindow(Ui_MainWindow):
    def setup_connections(self):
        self.doubleSpinBoxP.textChanged.connect(self.spinbox_changed)
        self.doubleSpinBoxV.textChanged.connect(self.spinbox_changed)
        self.doubleSpinBoxT.textChanged.connect(self.spinbox_changed)

        self.checkLatCap.stateChanged.connect(self.on_checkbox_state_changed)
        self.checkLatUpper.stateChanged.connect(self.on_checkbox_state_changed)
        self.checkRusCap.stateChanged.connect(self.on_checkbox_state_changed)
        self.checkRusUpper.stateChanged.connect(self.on_checkbox_state_changed)
        self.checkSimbols.stateChanged.connect(self.on_checkbox_state_changed)
        self.checkDigits.stateChanged.connect(self.on_checkbox_state_changed)

        self.btnGenerate.clicked.connect(self.on_btn_clicked)

        self.__A = 0
        self.__S = 0

    def spinbox_changed(self):
        print("test: spinbox_changed")

        # Переменные из DoubleSpinBox
        self.__P = self.doubleSpinBoxP.value()
        self.__V = self.doubleSpinBoxV.value()
        self.__T = self.doubleSpinBoxT.value()

        if self.__P <= 0:
            self.__P = 1
        if self.__V <= 0:
            self.__V = 1
        if self.__T <= 0:
            self.__T = 1

        # Считаем нижную границу пароля S*
        self.__S = math.ceil(math.fabs((self.__V * self.__T) / self.__P))
        print(f"S = {self.__S}")
        self.labelNumS.setText(str(self.__S))

        # Функция для счета длины пароля L
        self.__calculateL()

    def on_checkbox_state_changed(self):
        print("test: on_checkbox_state_changed")

        # Переменные из CheckBox
        # self.__latCap = self.checkLatCap.value()
        # self.__latUpper = self.checkLatUpper.value()
        # self.__rusCap = self.checkRusCap.value()
        # self.__rusUpper = self.checkRusUpper.value()
        # self.__simbols = self.checkSimbols.value()
        # self.__digits = self.checkDigits.value()

        # Считаем мощность алфавита A
        self.__A = self.checkLatCap.isChecked() * 26 + \
                   self.checkLatUpper.isChecked() * 26 + \
                   self.checkRusCap.isChecked() * 33 + \
                   self.checkRusUpper.isChecked() * 33 + \
                   self.checkSimbols.isChecked() * 33 + \
                   self.checkDigits.isChecked() * 10
        print(f"A = {self.__A}")

        # Вывод пароля в текстовое поле
        self.labelNumA.setText(str(self.__A))

        # Функция для счета длины пароля L
        self.__calculateL()

    def __calculateL(self):
        print("test: __calculateL")

        # Если поля пустые
        if not(self.__S and self.__A):
            return

        # Считаем длину пароля L
        self.__L = math.ceil(math.log(self.__S, self.__A))

        print(f"L = {self.__L}")

        # Выводим
        self.labelNumL.setText(str(self.__L))

    def on_btn_clicked(self):
        # Генерация пароля
        password = ""

        # Пул символов, из которых будет сгенерирован пароль
        pool = ""
        if self.checkLatCap.isChecked():
            pool += string.ascii_uppercase
        if self.checkLatUpper.isChecked():
            pool += string.ascii_lowercase
        if self.checkRusCap.isChecked():
            pool += 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
        if self.checkRusUpper.isChecked():
            pool += 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'
        if self.checkSimbols.isChecked():
            pool += "!@#$%^&*()_+-=[]{}|;:,.<>?`~"
        if self.checkDigits.isChecked():
            pool += string.digits

        if (pool):
            # Генерация пароля случайным образом из пула символов
            for _ in range(int(self.__L)):
                password += random.choice(pool)

            # Установка сгенерированного пароля в текстовое поле
            self.linePassword.setText(password)
        else:
            self.linePassword.setText("!!!Алфавит пустой!!!")

def main():
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = MainWindow()
    ui.setupUi(mainWindow)
    ui.setup_connections()
    mainWindow.show()
    sys.exit(app.exec())

if __name__ == '__main__':
    main()